-- Phase 3 Stage 6 (#44): Bronze domain sanity checks
-- Parameter: :batch_id

WITH reference_codes AS (
  SELECT CODE_SET_NAME, CODE_VALUE
  FROM FRAUDLENS.BRONZE.BRONZE_REFERENCE_DATA_CATALOG
  WHERE INGESTION_BATCH_ID = :batch_id
),
domain_checks AS (
  SELECT 'reference_domain' AS check_type, 'region' AS dataset_name, 'country_group_code' AS column_name, 'country_group_code' AS rule_name, COUNT_IF(src.COUNTRY_GROUP_CODE IS NOT NULL AND TRIM(src.COUNTRY_GROUP_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_REGION src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'country_group_code' AND ref.CODE_VALUE = src.COUNTRY_GROUP_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'branch_location' AS dataset_name, 'country_code' AS column_name, 'country_code' AS rule_name, COUNT_IF(src.COUNTRY_CODE IS NOT NULL AND TRIM(src.COUNTRY_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_BRANCH_LOCATION src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'country_code' AND ref.CODE_VALUE = src.COUNTRY_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'business_unit' AS dataset_name, 'business_unit_type' AS column_name, 'business_unit_type' AS rule_name, COUNT_IF(src.BUSINESS_UNIT_TYPE IS NOT NULL AND TRIM(src.BUSINESS_UNIT_TYPE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_BUSINESS_UNIT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'business_unit_type' AND ref.CODE_VALUE = src.BUSINESS_UNIT_TYPE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'party' AS dataset_name, 'party_type' AS column_name, 'party_type' AS rule_name, COUNT_IF(src.PARTY_TYPE IS NOT NULL AND TRIM(src.PARTY_TYPE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PARTY src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'party_type' AND ref.CODE_VALUE = src.PARTY_TYPE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'party' AS dataset_name, 'party_status' AS column_name, 'party_status' AS rule_name, COUNT_IF(src.PARTY_STATUS IS NOT NULL AND TRIM(src.PARTY_STATUS::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PARTY src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'party_status' AND ref.CODE_VALUE = src.PARTY_STATUS WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'party' AS dataset_name, 'domicile_country_code' AS column_name, 'country_code' AS rule_name, COUNT_IF(src.DOMICILE_COUNTRY_CODE IS NOT NULL AND TRIM(src.DOMICILE_COUNTRY_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PARTY src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'country_code' AND ref.CODE_VALUE = src.DOMICILE_COUNTRY_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'party' AS dataset_name, 'risk_segment_code' AS column_name, 'risk_segment_code' AS rule_name, COUNT_IF(src.RISK_SEGMENT_CODE IS NOT NULL AND TRIM(src.RISK_SEGMENT_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PARTY src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'risk_segment_code' AND ref.CODE_VALUE = src.RISK_SEGMENT_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'party' AS dataset_name, 'customer_segment_code' AS column_name, 'customer_segment_code' AS rule_name, COUNT_IF(src.CUSTOMER_SEGMENT_CODE IS NOT NULL AND TRIM(src.CUSTOMER_SEGMENT_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PARTY src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'customer_segment_code' AND ref.CODE_VALUE = src.CUSTOMER_SEGMENT_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'party' AS dataset_name, 'customer_type_code' AS column_name, 'customer_type_code' AS rule_name, COUNT_IF(src.CUSTOMER_TYPE_CODE IS NOT NULL AND TRIM(src.CUSTOMER_TYPE_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PARTY src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'customer_type_code' AND ref.CODE_VALUE = src.CUSTOMER_TYPE_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'party' AS dataset_name, 'industry_sector_code' AS column_name, 'industry_sector_code' AS rule_name, COUNT_IF(src.INDUSTRY_SECTOR_CODE IS NOT NULL AND TRIM(src.INDUSTRY_SECTOR_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PARTY src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'industry_sector_code' AND ref.CODE_VALUE = src.INDUSTRY_SECTOR_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'party_org_assignment' AS dataset_name, 'assignment_role_code' AS column_name, 'assignment_role_code' AS rule_name, COUNT_IF(src.ASSIGNMENT_ROLE_CODE IS NOT NULL AND TRIM(src.ASSIGNMENT_ROLE_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PARTY_ORG_ASSIGNMENT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'assignment_role_code' AND ref.CODE_VALUE = src.ASSIGNMENT_ROLE_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'deposit_account' AS dataset_name, 'account_status' AS column_name, 'account_status' AS rule_name, COUNT_IF(src.ACCOUNT_STATUS IS NOT NULL AND TRIM(src.ACCOUNT_STATUS::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_DEPOSIT_ACCOUNT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'account_status' AND ref.CODE_VALUE = src.ACCOUNT_STATUS WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'deposit_account' AS dataset_name, 'product_type_code' AS column_name, 'product_type_code' AS rule_name, COUNT_IF(src.PRODUCT_TYPE_CODE IS NOT NULL AND TRIM(src.PRODUCT_TYPE_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_DEPOSIT_ACCOUNT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'product_type_code' AND ref.CODE_VALUE = src.PRODUCT_TYPE_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'deposit_account' AS dataset_name, 'account_currency_code' AS column_name, 'currency_code' AS rule_name, COUNT_IF(src.ACCOUNT_CURRENCY_CODE IS NOT NULL AND TRIM(src.ACCOUNT_CURRENCY_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_DEPOSIT_ACCOUNT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'currency_code' AND ref.CODE_VALUE = src.ACCOUNT_CURRENCY_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'payment_card' AS dataset_name, 'card_status' AS column_name, 'card_status' AS rule_name, COUNT_IF(src.CARD_STATUS IS NOT NULL AND TRIM(src.CARD_STATUS::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PAYMENT_CARD src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'card_status' AND ref.CODE_VALUE = src.CARD_STATUS WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'payment_card' AS dataset_name, 'card_network_code' AS column_name, 'card_network_code' AS rule_name, COUNT_IF(src.CARD_NETWORK_CODE IS NOT NULL AND TRIM(src.CARD_NETWORK_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PAYMENT_CARD src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'card_network_code' AND ref.CODE_VALUE = src.CARD_NETWORK_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'device_profile' AS dataset_name, 'device_status' AS column_name, 'device_status' AS rule_name, COUNT_IF(src.DEVICE_STATUS IS NOT NULL AND TRIM(src.DEVICE_STATUS::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_DEVICE_PROFILE src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'device_status' AND ref.CODE_VALUE = src.DEVICE_STATUS WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'device_profile' AS dataset_name, 'operating_system_code' AS column_name, 'operating_system_code' AS rule_name, COUNT_IF(src.OPERATING_SYSTEM_CODE IS NOT NULL AND TRIM(src.OPERATING_SYSTEM_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_DEVICE_PROFILE src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'operating_system_code' AND ref.CODE_VALUE = src.OPERATING_SYSTEM_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'device_profile' AS dataset_name, 'device_risk_band' AS column_name, 'device_risk_band' AS rule_name, COUNT_IF(src.DEVICE_RISK_BAND IS NOT NULL AND TRIM(src.DEVICE_RISK_BAND::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_DEVICE_PROFILE src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'device_risk_band' AND ref.CODE_VALUE = src.DEVICE_RISK_BAND WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'channel_event' AS dataset_name, 'channel_code' AS column_name, 'channel_code' AS rule_name, COUNT_IF(src.CHANNEL_CODE IS NOT NULL AND TRIM(src.CHANNEL_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_CHANNEL_EVENT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'channel_code' AND ref.CODE_VALUE = src.CHANNEL_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'channel_event' AS dataset_name, 'event_country_code' AS column_name, 'country_code' AS rule_name, COUNT_IF(src.EVENT_COUNTRY_CODE IS NOT NULL AND TRIM(src.EVENT_COUNTRY_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_CHANNEL_EVENT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'country_code' AND ref.CODE_VALUE = src.EVENT_COUNTRY_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'channel_event' AS dataset_name, 'ip_country_code' AS column_name, 'country_code' AS rule_name, COUNT_IF(src.IP_COUNTRY_CODE IS NOT NULL AND TRIM(src.IP_COUNTRY_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_CHANNEL_EVENT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'country_code' AND ref.CODE_VALUE = src.IP_COUNTRY_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'channel_event' AS dataset_name, 'authentication_result_code' AS column_name, 'authentication_result_code' AS rule_name, COUNT_IF(src.AUTHENTICATION_RESULT_CODE IS NOT NULL AND TRIM(src.AUTHENTICATION_RESULT_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_CHANNEL_EVENT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'authentication_result_code' AND ref.CODE_VALUE = src.AUTHENTICATION_RESULT_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'channel_event' AS dataset_name, 'session_risk_code' AS column_name, 'session_risk_code' AS rule_name, COUNT_IF(src.SESSION_RISK_CODE IS NOT NULL AND TRIM(src.SESSION_RISK_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_CHANNEL_EVENT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'session_risk_code' AND ref.CODE_VALUE = src.SESSION_RISK_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'payment_instruction' AS dataset_name, 'instruction_status' AS column_name, 'instruction_status' AS rule_name, COUNT_IF(src.INSTRUCTION_STATUS IS NOT NULL AND TRIM(src.INSTRUCTION_STATUS::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PAYMENT_INSTRUCTION src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'instruction_status' AND ref.CODE_VALUE = src.INSTRUCTION_STATUS WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'payment_instruction' AS dataset_name, 'instructed_currency_code' AS column_name, 'currency_code' AS rule_name, COUNT_IF(src.INSTRUCTED_CURRENCY_CODE IS NOT NULL AND TRIM(src.INSTRUCTED_CURRENCY_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PAYMENT_INSTRUCTION src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'currency_code' AND ref.CODE_VALUE = src.INSTRUCTED_CURRENCY_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'payment_instruction' AS dataset_name, 'payment_purpose_code' AS column_name, 'payment_purpose_code' AS rule_name, COUNT_IF(src.PAYMENT_PURPOSE_CODE IS NOT NULL AND TRIM(src.PAYMENT_PURPOSE_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PAYMENT_INSTRUCTION src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'payment_purpose_code' AND ref.CODE_VALUE = src.PAYMENT_PURPOSE_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'payment_instruction' AS dataset_name, 'payment_rail_code' AS column_name, 'payment_rail_code' AS rule_name, COUNT_IF(src.PAYMENT_RAIL_CODE IS NOT NULL AND TRIM(src.PAYMENT_RAIL_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PAYMENT_INSTRUCTION src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'payment_rail_code' AND ref.CODE_VALUE = src.PAYMENT_RAIL_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'payment_instruction' AS dataset_name, 'merchant_country_code' AS column_name, 'country_code' AS rule_name, COUNT_IF(src.MERCHANT_COUNTRY_CODE IS NOT NULL AND TRIM(src.MERCHANT_COUNTRY_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PAYMENT_INSTRUCTION src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'country_code' AND ref.CODE_VALUE = src.MERCHANT_COUNTRY_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'payment_instruction' AS dataset_name, 'counterparty_bank_country_code' AS column_name, 'country_code' AS rule_name, COUNT_IF(src.COUNTERPARTY_BANK_COUNTRY_CODE IS NOT NULL AND TRIM(src.COUNTERPARTY_BANK_COUNTRY_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PAYMENT_INSTRUCTION src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'country_code' AND ref.CODE_VALUE = src.COUNTERPARTY_BANK_COUNTRY_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'payment_transaction' AS dataset_name, 'transaction_status' AS column_name, 'transaction_status' AS rule_name, COUNT_IF(src.TRANSACTION_STATUS IS NOT NULL AND TRIM(src.TRANSACTION_STATUS::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PAYMENT_TRANSACTION src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'transaction_status' AND ref.CODE_VALUE = src.TRANSACTION_STATUS WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'payment_transaction' AS dataset_name, 'transaction_currency_code' AS column_name, 'currency_code' AS rule_name, COUNT_IF(src.TRANSACTION_CURRENCY_CODE IS NOT NULL AND TRIM(src.TRANSACTION_CURRENCY_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PAYMENT_TRANSACTION src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'currency_code' AND ref.CODE_VALUE = src.TRANSACTION_CURRENCY_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'payment_transaction' AS dataset_name, 'merchant_category_code' AS column_name, 'merchant_category_code' AS rule_name, COUNT_IF(src.MERCHANT_CATEGORY_CODE IS NOT NULL AND TRIM(src.MERCHANT_CATEGORY_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PAYMENT_TRANSACTION src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'merchant_category_code' AND ref.CODE_VALUE = src.MERCHANT_CATEGORY_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'payment_transaction' AS dataset_name, 'transaction_direction_code' AS column_name, 'transaction_direction_code' AS rule_name, COUNT_IF(src.TRANSACTION_DIRECTION_CODE IS NOT NULL AND TRIM(src.TRANSACTION_DIRECTION_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PAYMENT_TRANSACTION src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'transaction_direction_code' AND ref.CODE_VALUE = src.TRANSACTION_DIRECTION_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'risk_signal' AS dataset_name, 'signal_type_code' AS column_name, 'signal_type_code' AS rule_name, COUNT_IF(src.SIGNAL_TYPE_CODE IS NOT NULL AND TRIM(src.SIGNAL_TYPE_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_RISK_SIGNAL src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'signal_type_code' AND ref.CODE_VALUE = src.SIGNAL_TYPE_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'risk_signal' AS dataset_name, 'risk_level' AS column_name, 'risk_level' AS rule_name, COUNT_IF(src.RISK_LEVEL IS NOT NULL AND TRIM(src.RISK_LEVEL::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_RISK_SIGNAL src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'risk_level' AND ref.CODE_VALUE = src.RISK_LEVEL WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'fraud_alert' AS dataset_name, 'alert_status' AS column_name, 'alert_status' AS rule_name, COUNT_IF(src.ALERT_STATUS IS NOT NULL AND TRIM(src.ALERT_STATUS::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_FRAUD_ALERT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'alert_status' AND ref.CODE_VALUE = src.ALERT_STATUS WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'fraud_alert' AS dataset_name, 'alert_severity' AS column_name, 'alert_severity' AS rule_name, COUNT_IF(src.ALERT_SEVERITY IS NOT NULL AND TRIM(src.ALERT_SEVERITY::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_FRAUD_ALERT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'alert_severity' AND ref.CODE_VALUE = src.ALERT_SEVERITY WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'fraud_alert' AS dataset_name, 'queue_code' AS column_name, 'queue_code' AS rule_name, COUNT_IF(src.QUEUE_CODE IS NOT NULL AND TRIM(src.QUEUE_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_FRAUD_ALERT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'queue_code' AND ref.CODE_VALUE = src.QUEUE_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'fraud_alert' AS dataset_name, 'alert_type_code' AS column_name, 'alert_type_code' AS rule_name, COUNT_IF(src.ALERT_TYPE_CODE IS NOT NULL AND TRIM(src.ALERT_TYPE_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_FRAUD_ALERT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'alert_type_code' AND ref.CODE_VALUE = src.ALERT_TYPE_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'fraud_alert' AS dataset_name, 'alert_source_code' AS column_name, 'alert_source_code' AS rule_name, COUNT_IF(src.ALERT_SOURCE_CODE IS NOT NULL AND TRIM(src.ALERT_SOURCE_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_FRAUD_ALERT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'alert_source_code' AND ref.CODE_VALUE = src.ALERT_SOURCE_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'fraud_case' AS dataset_name, 'case_status' AS column_name, 'case_status' AS rule_name, COUNT_IF(src.CASE_STATUS IS NOT NULL AND TRIM(src.CASE_STATUS::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_FRAUD_CASE src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'case_status' AND ref.CODE_VALUE = src.CASE_STATUS WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'fraud_case' AS dataset_name, 'case_type_code' AS column_name, 'case_type_code' AS rule_name, COUNT_IF(src.CASE_TYPE_CODE IS NOT NULL AND TRIM(src.CASE_TYPE_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_FRAUD_CASE src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'case_type_code' AND ref.CODE_VALUE = src.CASE_TYPE_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'fraud_case' AS dataset_name, 'case_priority_code' AS column_name, 'case_priority_code' AS rule_name, COUNT_IF(src.CASE_PRIORITY_CODE IS NOT NULL AND TRIM(src.CASE_PRIORITY_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_FRAUD_CASE src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'case_priority_code' AND ref.CODE_VALUE = src.CASE_PRIORITY_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'fraud_case' AS dataset_name, 'escalation_level_code' AS column_name, 'escalation_level_code' AS rule_name, COUNT_IF(src.ESCALATION_LEVEL_CODE IS NOT NULL AND TRIM(src.ESCALATION_LEVEL_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_FRAUD_CASE src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'escalation_level_code' AND ref.CODE_VALUE = src.ESCALATION_LEVEL_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'investigation_event' AS dataset_name, 'investigation_event_type' AS column_name, 'investigation_event_type' AS rule_name, COUNT_IF(src.INVESTIGATION_EVENT_TYPE IS NOT NULL AND TRIM(src.INVESTIGATION_EVENT_TYPE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_INVESTIGATION_EVENT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'investigation_event_type' AND ref.CODE_VALUE = src.INVESTIGATION_EVENT_TYPE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'investigation_event' AS dataset_name, 'event_result_code' AS column_name, 'event_result_code' AS rule_name, COUNT_IF(src.EVENT_RESULT_CODE IS NOT NULL AND TRIM(src.EVENT_RESULT_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_INVESTIGATION_EVENT src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'event_result_code' AND ref.CODE_VALUE = src.EVENT_RESULT_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'decision_record' AS dataset_name, 'decision_type' AS column_name, 'decision_type' AS rule_name, COUNT_IF(src.DECISION_TYPE IS NOT NULL AND TRIM(src.DECISION_TYPE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_DECISION_RECORD src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'decision_type' AND ref.CODE_VALUE = src.DECISION_TYPE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'decision_record' AS dataset_name, 'decision_status' AS column_name, 'decision_status' AS rule_name, COUNT_IF(src.DECISION_STATUS IS NOT NULL AND TRIM(src.DECISION_STATUS::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_DECISION_RECORD src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'decision_status' AND ref.CODE_VALUE = src.DECISION_STATUS WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'decision_record' AS dataset_name, 'decision_reason_code' AS column_name, 'decision_reason_code' AS rule_name, COUNT_IF(src.DECISION_REASON_CODE IS NOT NULL AND TRIM(src.DECISION_REASON_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_DECISION_RECORD src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'decision_reason_code' AND ref.CODE_VALUE = src.DECISION_REASON_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'decision_record' AS dataset_name, 'decision_channel_code' AS column_name, 'decision_channel_code' AS rule_name, COUNT_IF(src.DECISION_CHANNEL_CODE IS NOT NULL AND TRIM(src.DECISION_CHANNEL_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_DECISION_RECORD src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'decision_channel_code' AND ref.CODE_VALUE = src.DECISION_CHANNEL_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'case_disposition' AS dataset_name, 'disposition_code' AS column_name, 'disposition_code' AS rule_name, COUNT_IF(src.DISPOSITION_CODE IS NOT NULL AND TRIM(src.DISPOSITION_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_CASE_DISPOSITION src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'disposition_code' AND ref.CODE_VALUE = src.DISPOSITION_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'reference_domain' AS check_type, 'case_disposition' AS dataset_name, 'recovery_status_code' AS column_name, 'recovery_status_code' AS rule_name, COUNT_IF(src.RECOVERY_STATUS_CODE IS NOT NULL AND TRIM(src.RECOVERY_STATUS_CODE::STRING) <> '' AND ref.CODE_VALUE IS NULL) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_CASE_DISPOSITION src LEFT JOIN reference_codes ref ON ref.CODE_SET_NAME = 'recovery_status_code' AND ref.CODE_VALUE = src.RECOVERY_STATUS_CODE WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'numeric_sanity' AS check_type, 'payment_instruction' AS dataset_name, 'instructed_amount' AS column_name, 'gt_0' AS rule_name, COUNT_IF(src.INSTRUCTED_AMOUNT IS NOT NULL AND NOT (src.INSTRUCTED_AMOUNT > 0)) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PAYMENT_INSTRUCTION src WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'numeric_sanity' AS check_type, 'payment_transaction' AS dataset_name, 'booking_amount' AS column_name, 'gteq_0' AS rule_name, COUNT_IF(src.BOOKING_AMOUNT IS NOT NULL AND NOT (src.BOOKING_AMOUNT >= 0)) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_PAYMENT_TRANSACTION src WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'numeric_sanity' AS check_type, 'risk_signal' AS dataset_name, 'signal_score_amount' AS column_name, 'between_0_100' AS rule_name, COUNT_IF(src.SIGNAL_SCORE_AMOUNT IS NOT NULL AND (src.SIGNAL_SCORE_AMOUNT < 0 OR src.SIGNAL_SCORE_AMOUNT > 100)) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_RISK_SIGNAL src WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'numeric_sanity' AS check_type, 'investigation_event' AS dataset_name, 'elapsed_minutes' AS column_name, 'gteq_0' AS rule_name, COUNT_IF(src.ELAPSED_MINUTES IS NOT NULL AND NOT (src.ELAPSED_MINUTES >= 0)) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_INVESTIGATION_EVENT src WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'numeric_sanity' AS check_type, 'case_disposition' AS dataset_name, 'financial_impact_amount' AS column_name, 'gteq_0' AS rule_name, COUNT_IF(src.FINANCIAL_IMPACT_AMOUNT IS NOT NULL AND NOT (src.FINANCIAL_IMPACT_AMOUNT >= 0)) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_CASE_DISPOSITION src WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'numeric_sanity' AS check_type, 'case_disposition' AS dataset_name, 'loss_amount' AS column_name, 'gteq_0' AS rule_name, COUNT_IF(src.LOSS_AMOUNT IS NOT NULL AND NOT (src.LOSS_AMOUNT >= 0)) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_CASE_DISPOSITION src WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'numeric_sanity' AS check_type, 'case_disposition' AS dataset_name, 'recovered_amount' AS column_name, 'gteq_0' AS rule_name, COUNT_IF(src.RECOVERED_AMOUNT IS NOT NULL AND NOT (src.RECOVERED_AMOUNT >= 0)) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_CASE_DISPOSITION src WHERE src.INGESTION_BATCH_ID = :batch_id
  UNION ALL
  SELECT 'numeric_sanity' AS check_type, 'case_disposition' AS dataset_name, 'write_off_amount' AS column_name, 'gteq_0' AS rule_name, COUNT_IF(src.WRITE_OFF_AMOUNT IS NOT NULL AND NOT (src.WRITE_OFF_AMOUNT >= 0)) AS failed_count, COUNT(*) AS row_count FROM FRAUDLENS.BRONZE.BRONZE_CASE_DISPOSITION src WHERE src.INGESTION_BATCH_ID = :batch_id
)
SELECT
  check_type,
  dataset_name,
  column_name,
  rule_name,
  row_count,
  failed_count,
  CASE WHEN failed_count = 0 THEN 'pass' ELSE 'fail' END AS check_status
FROM domain_checks
ORDER BY check_type, dataset_name, column_name;
