-- Auto-generated Bronze DDL for dataset: case_disposition
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_CASE_DISPOSITION (
  DISPOSITION_ID VARCHAR,
  DECISION_ID VARCHAR,
  DISPOSITION_CODE VARCHAR,
  FINANCIAL_IMPACT_AMOUNT NUMBER(18,2),
  OUTCOME_AT TIMESTAMP_NTZ,
  LOSS_AMOUNT NUMBER(18,2),
  RECOVERED_AMOUNT NUMBER(18,2),
  WRITE_OFF_AMOUNT NUMBER(18,2),
  RECOVERY_STATUS_CODE VARCHAR,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
