-- Auto-generated Bronze DDL for dataset: payment_transaction
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_PAYMENT_TRANSACTION (
  PAYMENT_TRANSACTION_ID VARCHAR,
  PAYMENT_INSTRUCTION_ID VARCHAR,
  TRANSACTION_STATUS VARCHAR,
  BOOKING_AMOUNT NUMBER(18,2),
  TRANSACTION_CURRENCY_CODE VARCHAR,
  SETTLEMENT_AT TIMESTAMP_NTZ,
  MERCHANT_CATEGORY_CODE VARCHAR,
  REVERSAL_REASON_CODE VARCHAR,
  POSTED_DATE DATE,
  VALUE_DATE DATE,
  TRANSACTION_DIRECTION_CODE VARCHAR,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
