-- Auto-generated Bronze DDL for dataset: analyst_team
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_ANALYST_TEAM (
  ANALYST_TEAM_ID VARCHAR,
  ANALYST_TEAM_CODE VARCHAR,
  ANALYST_TEAM_NAME VARCHAR,
  BUSINESS_UNIT_ID VARCHAR,
  REGION_ID VARCHAR,
  IS_ACTIVE BOOLEAN,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
