-- Auto-generated Bronze DDL for dataset: reference_data_catalog
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_REFERENCE_DATA_CATALOG (
  CODE_SET_NAME VARCHAR,
  CODE_VALUE VARCHAR,
  CODE_DESCRIPTION VARCHAR,
  IS_ACTIVE BOOLEAN,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
