-- Auto-generated Bronze DDL for dataset: deposit_account
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_DEPOSIT_ACCOUNT (
  DEPOSIT_ACCOUNT_ID VARCHAR,
  ACCOUNT_STATUS VARCHAR,
  PRODUCT_TYPE_CODE VARCHAR,
  PRIMARY_PARTY_ID VARCHAR,
  ACCOUNT_CURRENCY_CODE VARCHAR,
  AVAILABLE_BALANCE_AMOUNT NUMBER(18,2),
  OPENED_AT TIMESTAMP_NTZ,
  OPENED_BRANCH_ID VARCHAR,
  SERVICING_BUSINESS_UNIT_ID VARCHAR,
  ACCOUNT_REGION_ID VARCHAR,
  CLOSED_AT TIMESTAMP_NTZ,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
