-- Auto-generated Bronze DDL for dataset: party_org_assignment
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_PARTY_ORG_ASSIGNMENT (
  PARTY_ORG_ASSIGNMENT_ID VARCHAR,
  PARTY_ID VARCHAR,
  BUSINESS_UNIT_ID VARCHAR,
  ANALYST_TEAM_ID VARCHAR,
  BRANCH_ID VARCHAR,
  ASSIGNMENT_ROLE_CODE VARCHAR,
  EFFECTIVE_FROM_AT TIMESTAMP_NTZ,
  EFFECTIVE_TO_AT TIMESTAMP_NTZ,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
