-- Auto-generated Bronze DDL for dataset: business_unit
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_BUSINESS_UNIT (
  BUSINESS_UNIT_ID VARCHAR,
  BUSINESS_UNIT_CODE VARCHAR,
  BUSINESS_UNIT_NAME VARCHAR,
  BUSINESS_UNIT_TYPE VARCHAR,
  REGION_ID VARCHAR,
  IS_ACTIVE BOOLEAN,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
