-- Auto-generated Bronze DDL for dataset: calendar_day
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_CALENDAR_DAY (
  CALENDAR_DATE DATE,
  CALENDAR_YEAR NUMBER(9,0),
  CALENDAR_QUARTER NUMBER(9,0),
  CALENDAR_MONTH NUMBER(9,0),
  CALENDAR_MONTH_NAME VARCHAR,
  WEEK_OF_YEAR NUMBER(9,0),
  DAY_OF_WEEK NUMBER(9,0),
  DAY_NAME VARCHAR,
  IS_WEEKEND BOOLEAN,
  IS_MONTH_END BOOLEAN,
  IS_QUARTER_END BOOLEAN,
  IS_HOLIDAY BOOLEAN,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
