-- Auto-generated Bronze DDL for dataset: branch_territory
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_BRANCH_TERRITORY (
  BRANCH_TERRITORY_ID VARCHAR,
  BRANCH_TERRITORY_CODE VARCHAR,
  BRANCH_TERRITORY_NAME VARCHAR,
  REGION_ID VARCHAR,
  IS_ACTIVE BOOLEAN,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
