-- Auto-generated Bronze DDL for dataset: decision_record
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_DECISION_RECORD (
  DECISION_ID VARCHAR,
  FRAUD_CASE_ID VARCHAR,
  DECISION_TYPE VARCHAR,
  DECISION_STATUS VARCHAR,
  DECISION_MAKER_PARTY_ID VARCHAR,
  DECIDED_AT TIMESTAMP_NTZ,
  DECISION_REASON_CODE VARCHAR,
  DECISION_CHANNEL_CODE VARCHAR,
  POLICY_NAME VARCHAR,
  RULE_SET_VERSION VARCHAR,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
