-- Auto-generated Bronze DDL for dataset: device_profile
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_DEVICE_PROFILE (
  DEVICE_ID VARCHAR,
  DEVICE_STATUS VARCHAR,
  OPERATING_SYSTEM_CODE VARCHAR,
  DEVICE_RISK_BAND VARCHAR,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
