-- Auto-generated Bronze DDL for dataset: investigation_event
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_INVESTIGATION_EVENT (
  INVESTIGATION_EVENT_ID VARCHAR,
  FRAUD_CASE_ID VARCHAR,
  INVESTIGATION_EVENT_TYPE VARCHAR,
  ACTOR_PARTY_ID VARCHAR,
  EVENT_AT TIMESTAMP_NTZ,
  EVENT_RESULT_CODE VARCHAR,
  ELAPSED_MINUTES NUMBER(9,0),
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
