-- Auto-generated Bronze DDL for dataset: risk_signal
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_RISK_SIGNAL (
  RISK_SIGNAL_ID VARCHAR,
  PAYMENT_INSTRUCTION_ID VARCHAR,
  SIGNAL_TYPE_CODE VARCHAR,
  SIGNAL_SCORE_AMOUNT NUMBER(18,2),
  RISK_LEVEL VARCHAR,
  EVENT_AT TIMESTAMP_NTZ,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
