-- Auto-generated Bronze DDL for dataset: region
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_REGION (
  REGION_ID VARCHAR,
  REGION_CODE VARCHAR,
  REGION_NAME VARCHAR,
  COUNTRY_GROUP_CODE VARCHAR,
  IS_ACTIVE BOOLEAN,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
