-- Auto-generated Bronze DDL for dataset: branch_location
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_BRANCH_LOCATION (
  BRANCH_ID VARCHAR,
  BRANCH_CODE VARCHAR,
  BRANCH_NAME VARCHAR,
  BRANCH_TERRITORY_ID VARCHAR,
  REGION_ID VARCHAR,
  COUNTRY_CODE VARCHAR,
  CITY_NAME VARCHAR,
  IS_ACTIVE BOOLEAN,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
