-- Auto-generated Bronze DDL for dataset: payment_instruction
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_PAYMENT_INSTRUCTION (
  PAYMENT_INSTRUCTION_ID VARCHAR,
  INSTRUCTION_STATUS VARCHAR,
  DEBTOR_ACCOUNT_ID VARCHAR,
  DEBTOR_PARTY_ID VARCHAR,
  CREDITOR_PARTY_ID VARCHAR,
  INSTRUCTED_AMOUNT NUMBER(18,2),
  INSTRUCTED_CURRENCY_CODE VARCHAR,
  PAYMENT_PURPOSE_CODE VARCHAR,
  CHANNEL_EVENT_ID VARCHAR,
  CARD_ID VARCHAR,
  DEVICE_ID VARCHAR,
  EVENT_AT TIMESTAMP_NTZ,
  PAYMENT_RAIL_CODE VARCHAR,
  IS_CROSS_BORDER BOOLEAN,
  MERCHANT_COUNTRY_CODE VARCHAR,
  COUNTERPARTY_BANK_COUNTRY_CODE VARCHAR,
  BOOKING_DATE DATE,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
