-- Auto-generated Bronze DDL for dataset: payment_card
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_PAYMENT_CARD (
  CARD_ID VARCHAR,
  LINKED_ACCOUNT_ID VARCHAR,
  CARD_STATUS VARCHAR,
  CARD_NETWORK_CODE VARCHAR,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
