-- Auto-generated Bronze DDL for dataset: fraud_alert
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_FRAUD_ALERT (
  FRAUD_ALERT_ID VARCHAR,
  RISK_SIGNAL_ID VARCHAR,
  ALERT_STATUS VARCHAR,
  ALERT_SEVERITY VARCHAR,
  QUEUE_CODE VARCHAR,
  CREATED_AT TIMESTAMP_NTZ,
  ALERT_TYPE_CODE VARCHAR,
  ALERT_SOURCE_CODE VARCHAR,
  OWNING_BUSINESS_UNIT_ID VARCHAR,
  OWNING_ANALYST_TEAM_ID VARCHAR,
  SERVICE_LEVEL_DUE_AT TIMESTAMP_NTZ,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
