-- Auto-generated Bronze DDL for dataset: fraud_case
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_FRAUD_CASE (
  FRAUD_CASE_ID VARCHAR,
  PRIMARY_ALERT_ID VARCHAR,
  CASE_STATUS VARCHAR,
  ASSIGNED_ANALYST_PARTY_ID VARCHAR,
  OPENED_AT TIMESTAMP_NTZ,
  CLOSED_AT TIMESTAMP_NTZ,
  CASE_TYPE_CODE VARCHAR,
  CASE_PRIORITY_CODE VARCHAR,
  OWNING_BUSINESS_UNIT_ID VARCHAR,
  OWNING_ANALYST_TEAM_ID VARCHAR,
  HANDLING_REGION_ID VARCHAR,
  ESCALATION_LEVEL_CODE VARCHAR,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
