-- Auto-generated Bronze DDL for dataset: channel_event
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_CHANNEL_EVENT (
  CHANNEL_EVENT_ID VARCHAR,
  CHANNEL_CODE VARCHAR,
  SESSION_ID VARCHAR,
  BRANCH_ID VARCHAR,
  EVENT_AT TIMESTAMP_NTZ,
  EVENT_COUNTRY_CODE VARCHAR,
  IP_COUNTRY_CODE VARCHAR,
  AUTHENTICATION_RESULT_CODE VARCHAR,
  SESSION_RISK_CODE VARCHAR,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
