-- Auto-generated Bronze DDL for dataset: party
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_PARTY (
  PARTY_ID VARCHAR,
  PARTY_TYPE VARCHAR,
  PARTY_STATUS VARCHAR,
  DOMICILE_COUNTRY_CODE VARCHAR,
  RISK_SEGMENT_CODE VARCHAR,
  CUSTOMER_SEGMENT_CODE VARCHAR,
  CUSTOMER_TYPE_CODE VARCHAR,
  INDUSTRY_SECTOR_CODE VARCHAR,
  RESIDENCY_REGION_ID VARCHAR,
  CUSTOMER_SINCE_AT TIMESTAMP_NTZ,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
