from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from _config_loader import load_profile
from _dataset_layout import DATASET_ORDER, bronze_table_name


def _latest_batch_id(data_root: str) -> str:
    batches_dir = Path(data_root) / "batches"
    if not batches_dir.exists():
        raise FileNotFoundError(f"Batches folder not found: {batches_dir}")
    candidates = [item.name for item in batches_dir.iterdir() if item.is_dir()]
    if not candidates:
        raise FileNotFoundError(f"No batch directories found under: {batches_dir}")
    return sorted(candidates)[-1]


def _resolve_batch_id(batch_id: str, data_root: str) -> str:
    value = batch_id.strip()
    if value.lower() == "latest":
        return _latest_batch_id(data_root)
    return value


def _manifest_path(batch_id: str, data_root: str) -> Path:
    return Path(data_root) / "batches" / batch_id / "control" / "manifest.json"


def _load_manifest(batch_id: str, data_root: str) -> dict[str, Any]:
    manifest_file = _manifest_path(batch_id, data_root)
    if not manifest_file.exists():
        raise FileNotFoundError(f"Manifest not found for batch '{batch_id}': {manifest_file}")
    payload = json.loads(manifest_file.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Manifest content is invalid JSON object: {manifest_file}")
    return payload


def _warehouse_context(profile_name: str | None) -> dict[str, str]:
    profile = load_profile(profile_name)
    warehouse = profile.get("warehouse", {})
    schemas = warehouse.get("schemas", {})
    return {
        "database": str(warehouse.get("database", "FRAUDLENS")).upper(),
        "bronze_schema": str(schemas.get("bronze", "BRONZE")).upper(),
    }


def _expected_counts(manifest: dict[str, Any]) -> dict[str, int]:
    datasets = manifest.get("datasets", {})
    if not isinstance(datasets, dict):
        return {}
    result: dict[str, int] = {}
    for dataset, payload in datasets.items():
        if not isinstance(payload, dict):
            continue
        row_count = payload.get("row_count")
        try:
            result[dataset] = int(row_count)
        except (TypeError, ValueError):
            continue
    return result


def _row_count_sql(
    batch_id: str,
    database: str,
    schema: str,
    expected_counts: dict[str, int],
) -> str:
    expected_values = [
        f"    ('{dataset}', {expected_counts[dataset]})"
        for dataset in DATASET_ORDER
        if dataset in expected_counts
    ]
    actual_blocks = [
        (
            f"  SELECT '{dataset}' AS dataset_name, COUNT(*) AS actual_row_count\n"
            f"  FROM {database}.{schema}.{bronze_table_name(dataset)}\n"
            f"  WHERE INGESTION_BATCH_ID = '{batch_id}'"
        )
        for dataset in DATASET_ORDER
        if dataset in expected_counts
    ]
    if not expected_values:
        raise ValueError("Manifest has no dataset row counts to reconcile.")
    return (
        "-- Auto-generated by validate_load.py\n"
        f"-- Batch: {batch_id}\n\n"
        "WITH expected_rows AS (\n"
        "  SELECT column1::VARCHAR AS dataset_name, column2::NUMBER AS expected_row_count\n"
        "  FROM VALUES\n"
        + ",\n".join(expected_values)
        + "\n),\n"
        "actual_rows AS (\n"
        + "\n  UNION ALL\n".join(actual_blocks)
        + "\n)\n"
        "SELECT\n"
        "  e.dataset_name,\n"
        "  e.expected_row_count,\n"
        "  COALESCE(a.actual_row_count, 0) AS actual_row_count,\n"
        "  COALESCE(a.actual_row_count, 0) - e.expected_row_count AS row_delta,\n"
        "  CASE\n"
        "    WHEN COALESCE(a.actual_row_count, 0) = e.expected_row_count THEN 'pass'\n"
        "    ELSE 'fail'\n"
        "  END AS check_status\n"
        "FROM expected_rows e\n"
        "LEFT JOIN actual_rows a ON a.dataset_name = e.dataset_name\n"
        "ORDER BY e.dataset_name;\n"
    )


def _output_dir() -> Path:
    target = Path("warehouse/snowflake-warehouse-setup/sql/runtime/validation")
    target.mkdir(parents=True, exist_ok=True)
    return target


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate batch-specific Bronze load validation SQL inputs.")
    parser.add_argument("--batch-id", required=True, help="FraudLens batch id, or 'latest'")
    parser.add_argument("--profile", choices=["local", "cloud"], default=None, help="Config profile override")
    parser.add_argument("--data-root", default="data", help="Root directory that contains batches/")
    parser.add_argument(
        "--emit-row-count-sql",
        action="store_true",
        help="Write executable batch-specific row-count reconciliation SQL",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    batch_id = _resolve_batch_id(args.batch_id, args.data_root)
    manifest = _load_manifest(batch_id, args.data_root)
    expected_counts = _expected_counts(manifest)

    if args.emit_row_count_sql:
        context = _warehouse_context(args.profile)
        target = _output_dir() / f"bronze_row_count_reconciliation_{batch_id}.sql"
        sql_text = _row_count_sql(
            batch_id=batch_id,
            database=context["database"],
            schema=context["bronze_schema"],
            expected_counts=expected_counts,
        )
        target.write_text(sql_text, encoding="utf-8")
        print(f"Wrote row-count SQL: {target}")

    summary = {
        "batch_id": batch_id,
        "datasets_in_manifest": len(expected_counts),
        "dataset_names": [dataset for dataset in DATASET_ORDER if dataset in expected_counts],
    }
    print(json.dumps(summary))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
