-- Auto-generated Bronze COPY INTO for dataset: device_profile
SET BATCH_ID = '<replace_with_batch_id>';

COPY INTO FRAUDLENS.BRONZE.BRONZE_DEVICE_PROFILE (
  DEVICE_ID,
  DEVICE_STATUS,
  OPERATING_SYSTEM_CODE,
  DEVICE_RISK_BAND,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/device_profile.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';
