-- Auto-generated Bronze COPY INTO for dataset: deposit_account
SET BATCH_ID = '<replace_with_batch_id>';

COPY INTO FRAUDLENS.BRONZE.BRONZE_DEPOSIT_ACCOUNT (
  DEPOSIT_ACCOUNT_ID,
  ACCOUNT_STATUS,
  PRODUCT_TYPE_CODE,
  PRIMARY_PARTY_ID,
  ACCOUNT_CURRENCY_CODE,
  AVAILABLE_BALANCE_AMOUNT,
  OPENED_AT,
  OPENED_BRANCH_ID,
  SERVICING_BUSINESS_UNIT_ID,
  ACCOUNT_REGION_ID,
  CLOSED_AT,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    t.$10,
    t.$11,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/deposit_account.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';
