-- Auto-generated Bronze COPY INTO for dataset: fraud_case
SET BATCH_ID = '<replace_with_batch_id>';

COPY INTO FRAUDLENS.BRONZE.BRONZE_FRAUD_CASE (
  FRAUD_CASE_ID,
  PRIMARY_ALERT_ID,
  CASE_STATUS,
  ASSIGNED_ANALYST_PARTY_ID,
  OPENED_AT,
  CLOSED_AT,
  CASE_TYPE_CODE,
  CASE_PRIORITY_CODE,
  OWNING_BUSINESS_UNIT_ID,
  OWNING_ANALYST_TEAM_ID,
  HANDLING_REGION_ID,
  ESCALATION_LEVEL_CODE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    t.$10,
    t.$11,
    t.$12,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/fraud_case.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';
