-- Auto-generated Bronze COPY INTO for dataset: payment_transaction
SET BATCH_ID = '<replace_with_batch_id>';

COPY INTO FRAUDLENS.BRONZE.BRONZE_PAYMENT_TRANSACTION (
  PAYMENT_TRANSACTION_ID,
  PAYMENT_INSTRUCTION_ID,
  TRANSACTION_STATUS,
  BOOKING_AMOUNT,
  TRANSACTION_CURRENCY_CODE,
  SETTLEMENT_AT,
  MERCHANT_CATEGORY_CODE,
  REVERSAL_REASON_CODE,
  POSTED_DATE,
  VALUE_DATE,
  TRANSACTION_DIRECTION_CODE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    t.$10,
    t.$11,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/payment_transaction.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';
