-- Auto-generated Bronze COPY INTO for dataset: party
SET BATCH_ID = '<replace_with_batch_id>';

COPY INTO FRAUDLENS.BRONZE.BRONZE_PARTY (
  PARTY_ID,
  PARTY_TYPE,
  PARTY_STATUS,
  DOMICILE_COUNTRY_CODE,
  RISK_SEGMENT_CODE,
  CUSTOMER_SEGMENT_CODE,
  CUSTOMER_TYPE_CODE,
  INDUSTRY_SECTOR_CODE,
  RESIDENCY_REGION_ID,
  CUSTOMER_SINCE_AT,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    t.$10,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/party.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';
