-- Auto-generated Bronze COPY INTO for dataset: payment_instruction
SET BATCH_ID = '<replace_with_batch_id>';

COPY INTO FRAUDLENS.BRONZE.BRONZE_PAYMENT_INSTRUCTION (
  PAYMENT_INSTRUCTION_ID,
  INSTRUCTION_STATUS,
  DEBTOR_ACCOUNT_ID,
  DEBTOR_PARTY_ID,
  CREDITOR_PARTY_ID,
  INSTRUCTED_AMOUNT,
  INSTRUCTED_CURRENCY_CODE,
  PAYMENT_PURPOSE_CODE,
  CHANNEL_EVENT_ID,
  CARD_ID,
  DEVICE_ID,
  EVENT_AT,
  PAYMENT_RAIL_CODE,
  IS_CROSS_BORDER,
  MERCHANT_COUNTRY_CODE,
  COUNTERPARTY_BANK_COUNTRY_CODE,
  BOOKING_DATE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    t.$10,
    t.$11,
    t.$12,
    t.$13,
    t.$14,
    t.$15,
    t.$16,
    t.$17,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/payment_instruction.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';
