-- Auto-generated Bronze COPY INTO for dataset: investigation_event
SET BATCH_ID = '<replace_with_batch_id>';

COPY INTO FRAUDLENS.BRONZE.BRONZE_INVESTIGATION_EVENT (
  INVESTIGATION_EVENT_ID,
  FRAUD_CASE_ID,
  INVESTIGATION_EVENT_TYPE,
  ACTOR_PARTY_ID,
  EVENT_AT,
  EVENT_RESULT_CODE,
  ELAPSED_MINUTES,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/investigation_event.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';
