-- Auto-generated Bronze COPY INTO for dataset: risk_signal
SET BATCH_ID = '<replace_with_batch_id>';

COPY INTO FRAUDLENS.BRONZE.BRONZE_RISK_SIGNAL (
  RISK_SIGNAL_ID,
  PAYMENT_INSTRUCTION_ID,
  SIGNAL_TYPE_CODE,
  SIGNAL_SCORE_AMOUNT,
  RISK_LEVEL,
  EVENT_AT,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/risk_signal.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';
