-- Auto-generated Bronze COPY INTO for dataset: case_disposition
SET BATCH_ID = '<replace_with_batch_id>';

COPY INTO FRAUDLENS.BRONZE.BRONZE_CASE_DISPOSITION (
  DISPOSITION_ID,
  DECISION_ID,
  DISPOSITION_CODE,
  FINANCIAL_IMPACT_AMOUNT,
  OUTCOME_AT,
  LOSS_AMOUNT,
  RECOVERED_AMOUNT,
  WRITE_OFF_AMOUNT,
  RECOVERY_STATUS_CODE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/case_disposition.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';
