-- Stage 4 (#42): batch-based MinIO ingestion for Bronze dimensions

SET BATCH_ID = '<replace_with_batch_id>';

-- dataset: reference_data_catalog
COPY INTO FRAUDLENS.BRONZE.BRONZE_REFERENCE_DATA_CATALOG (
  CODE_SET_NAME,
  CODE_VALUE,
  CODE_DESCRIPTION,
  IS_ACTIVE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/reference_data_catalog.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: calendar_day
COPY INTO FRAUDLENS.BRONZE.BRONZE_CALENDAR_DAY (
  CALENDAR_DATE,
  CALENDAR_YEAR,
  CALENDAR_QUARTER,
  CALENDAR_MONTH,
  CALENDAR_MONTH_NAME,
  WEEK_OF_YEAR,
  DAY_OF_WEEK,
  DAY_NAME,
  IS_WEEKEND,
  IS_MONTH_END,
  IS_QUARTER_END,
  IS_HOLIDAY,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    t.$10,
    t.$11,
    t.$12,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/calendar_day.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: region
COPY INTO FRAUDLENS.BRONZE.BRONZE_REGION (
  REGION_ID,
  REGION_CODE,
  REGION_NAME,
  COUNTRY_GROUP_CODE,
  IS_ACTIVE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/region.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: branch_territory
COPY INTO FRAUDLENS.BRONZE.BRONZE_BRANCH_TERRITORY (
  BRANCH_TERRITORY_ID,
  BRANCH_TERRITORY_CODE,
  BRANCH_TERRITORY_NAME,
  REGION_ID,
  IS_ACTIVE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/branch_territory.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: branch_location
COPY INTO FRAUDLENS.BRONZE.BRONZE_BRANCH_LOCATION (
  BRANCH_ID,
  BRANCH_CODE,
  BRANCH_NAME,
  BRANCH_TERRITORY_ID,
  REGION_ID,
  COUNTRY_CODE,
  CITY_NAME,
  IS_ACTIVE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/branch_location.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: business_unit
COPY INTO FRAUDLENS.BRONZE.BRONZE_BUSINESS_UNIT (
  BUSINESS_UNIT_ID,
  BUSINESS_UNIT_CODE,
  BUSINESS_UNIT_NAME,
  BUSINESS_UNIT_TYPE,
  REGION_ID,
  IS_ACTIVE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/business_unit.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: analyst_team
COPY INTO FRAUDLENS.BRONZE.BRONZE_ANALYST_TEAM (
  ANALYST_TEAM_ID,
  ANALYST_TEAM_CODE,
  ANALYST_TEAM_NAME,
  BUSINESS_UNIT_ID,
  REGION_ID,
  IS_ACTIVE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/analyst_team.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';
