-- Stage 4 (#42): batch-based MinIO ingestion for Bronze core/fraud datasets

SET BATCH_ID = '<replace_with_batch_id>';

-- dataset: party
COPY INTO FRAUDLENS.BRONZE.BRONZE_PARTY (
  PARTY_ID,
  PARTY_TYPE,
  PARTY_STATUS,
  DOMICILE_COUNTRY_CODE,
  RISK_SEGMENT_CODE,
  CUSTOMER_SEGMENT_CODE,
  CUSTOMER_TYPE_CODE,
  INDUSTRY_SECTOR_CODE,
  RESIDENCY_REGION_ID,
  CUSTOMER_SINCE_AT,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    t.$10,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/party.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: party_org_assignment
COPY INTO FRAUDLENS.BRONZE.BRONZE_PARTY_ORG_ASSIGNMENT (
  PARTY_ORG_ASSIGNMENT_ID,
  PARTY_ID,
  BUSINESS_UNIT_ID,
  ANALYST_TEAM_ID,
  BRANCH_ID,
  ASSIGNMENT_ROLE_CODE,
  EFFECTIVE_FROM_AT,
  EFFECTIVE_TO_AT,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/party_org_assignment.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: deposit_account
COPY INTO FRAUDLENS.BRONZE.BRONZE_DEPOSIT_ACCOUNT (
  DEPOSIT_ACCOUNT_ID,
  ACCOUNT_STATUS,
  PRODUCT_TYPE_CODE,
  PRIMARY_PARTY_ID,
  ACCOUNT_CURRENCY_CODE,
  AVAILABLE_BALANCE_AMOUNT,
  OPENED_AT,
  OPENED_BRANCH_ID,
  SERVICING_BUSINESS_UNIT_ID,
  ACCOUNT_REGION_ID,
  CLOSED_AT,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    t.$10,
    t.$11,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/deposit_account.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: payment_card
COPY INTO FRAUDLENS.BRONZE.BRONZE_PAYMENT_CARD (
  CARD_ID,
  LINKED_ACCOUNT_ID,
  CARD_STATUS,
  CARD_NETWORK_CODE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/payment_card.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: device_profile
COPY INTO FRAUDLENS.BRONZE.BRONZE_DEVICE_PROFILE (
  DEVICE_ID,
  DEVICE_STATUS,
  OPERATING_SYSTEM_CODE,
  DEVICE_RISK_BAND,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/device_profile.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: channel_event
COPY INTO FRAUDLENS.BRONZE.BRONZE_CHANNEL_EVENT (
  CHANNEL_EVENT_ID,
  CHANNEL_CODE,
  SESSION_ID,
  BRANCH_ID,
  EVENT_AT,
  EVENT_COUNTRY_CODE,
  IP_COUNTRY_CODE,
  AUTHENTICATION_RESULT_CODE,
  SESSION_RISK_CODE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/channel_event.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: payment_instruction
COPY INTO FRAUDLENS.BRONZE.BRONZE_PAYMENT_INSTRUCTION (
  PAYMENT_INSTRUCTION_ID,
  INSTRUCTION_STATUS,
  DEBTOR_ACCOUNT_ID,
  DEBTOR_PARTY_ID,
  CREDITOR_PARTY_ID,
  INSTRUCTED_AMOUNT,
  INSTRUCTED_CURRENCY_CODE,
  PAYMENT_PURPOSE_CODE,
  CHANNEL_EVENT_ID,
  CARD_ID,
  DEVICE_ID,
  EVENT_AT,
  PAYMENT_RAIL_CODE,
  IS_CROSS_BORDER,
  MERCHANT_COUNTRY_CODE,
  COUNTERPARTY_BANK_COUNTRY_CODE,
  BOOKING_DATE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    t.$10,
    t.$11,
    t.$12,
    t.$13,
    t.$14,
    t.$15,
    t.$16,
    t.$17,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/payment_instruction.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: payment_transaction
COPY INTO FRAUDLENS.BRONZE.BRONZE_PAYMENT_TRANSACTION (
  PAYMENT_TRANSACTION_ID,
  PAYMENT_INSTRUCTION_ID,
  TRANSACTION_STATUS,
  BOOKING_AMOUNT,
  TRANSACTION_CURRENCY_CODE,
  SETTLEMENT_AT,
  MERCHANT_CATEGORY_CODE,
  REVERSAL_REASON_CODE,
  POSTED_DATE,
  VALUE_DATE,
  TRANSACTION_DIRECTION_CODE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    t.$10,
    t.$11,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/payment_transaction.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: risk_signal
COPY INTO FRAUDLENS.BRONZE.BRONZE_RISK_SIGNAL (
  RISK_SIGNAL_ID,
  PAYMENT_INSTRUCTION_ID,
  SIGNAL_TYPE_CODE,
  SIGNAL_SCORE_AMOUNT,
  RISK_LEVEL,
  EVENT_AT,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/risk_signal.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: fraud_alert
COPY INTO FRAUDLENS.BRONZE.BRONZE_FRAUD_ALERT (
  FRAUD_ALERT_ID,
  RISK_SIGNAL_ID,
  ALERT_STATUS,
  ALERT_SEVERITY,
  QUEUE_CODE,
  CREATED_AT,
  ALERT_TYPE_CODE,
  ALERT_SOURCE_CODE,
  OWNING_BUSINESS_UNIT_ID,
  OWNING_ANALYST_TEAM_ID,
  SERVICE_LEVEL_DUE_AT,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    t.$10,
    t.$11,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/fraud_alert.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: fraud_case
COPY INTO FRAUDLENS.BRONZE.BRONZE_FRAUD_CASE (
  FRAUD_CASE_ID,
  PRIMARY_ALERT_ID,
  CASE_STATUS,
  ASSIGNED_ANALYST_PARTY_ID,
  OPENED_AT,
  CLOSED_AT,
  CASE_TYPE_CODE,
  CASE_PRIORITY_CODE,
  OWNING_BUSINESS_UNIT_ID,
  OWNING_ANALYST_TEAM_ID,
  HANDLING_REGION_ID,
  ESCALATION_LEVEL_CODE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    t.$10,
    t.$11,
    t.$12,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/fraud_case.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: investigation_event
COPY INTO FRAUDLENS.BRONZE.BRONZE_INVESTIGATION_EVENT (
  INVESTIGATION_EVENT_ID,
  FRAUD_CASE_ID,
  INVESTIGATION_EVENT_TYPE,
  ACTOR_PARTY_ID,
  EVENT_AT,
  EVENT_RESULT_CODE,
  ELAPSED_MINUTES,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/investigation_event.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: decision_record
COPY INTO FRAUDLENS.BRONZE.BRONZE_DECISION_RECORD (
  DECISION_ID,
  FRAUD_CASE_ID,
  DECISION_TYPE,
  DECISION_STATUS,
  DECISION_MAKER_PARTY_ID,
  DECIDED_AT,
  DECISION_REASON_CODE,
  DECISION_CHANNEL_CODE,
  POLICY_NAME,
  RULE_SET_VERSION,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    t.$10,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/decision_record.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';

-- dataset: case_disposition
COPY INTO FRAUDLENS.BRONZE.BRONZE_CASE_DISPOSITION (
  DISPOSITION_ID,
  DECISION_ID,
  DISPOSITION_CODE,
  FINANCIAL_IMPACT_AMOUNT,
  OUTCOME_AT,
  LOSS_AMOUNT,
  RECOVERED_AMOUNT,
  WRITE_OFF_AMOUNT,
  RECOVERY_STATUS_CODE,
  INGESTION_BATCH_ID,
  SOURCE_FILE_NAME,
  INGESTED_AT_UTC
)
FROM (
  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    $BATCH_ID,
    METADATA$FILENAME,
    CURRENT_TIMESTAMP()
  FROM @FRAUDLENS.BRONZE.STG_BRONZE_MINIO_RAW/$BATCH_ID/raw_zone/csv/case_disposition.csv (FILE_FORMAT => FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1) t
)
ON_ERROR = 'ABORT_STATEMENT';
