-- Scaffold-only GOLD DDL for dataset: payment_card
-- TODO: replace placeholder columns with curated model design.
CREATE TABLE IF NOT EXISTS FRAUDLENS.GOLD.GOLD_PAYMENT_CARD (
  PLACEHOLDER_RECORD_ID VARCHAR,
  SOURCE_BATCH_ID VARCHAR,
  PIPELINE_CREATED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
