-- Scaffold-only GOLD DDL for dataset: analyst_team
-- TODO: replace placeholder columns with curated model design.
CREATE TABLE IF NOT EXISTS FRAUDLENS.GOLD.GOLD_ANALYST_TEAM (
  PLACEHOLDER_RECORD_ID VARCHAR,
  SOURCE_BATCH_ID VARCHAR,
  PIPELINE_CREATED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
