-- Scaffold-only SILVER DDL for dataset: calendar_day
-- TODO: replace placeholder columns with curated model design.
CREATE TABLE IF NOT EXISTS FRAUDLENS.SILVER.SILVER_CALENDAR_DAY (
  PLACEHOLDER_RECORD_ID VARCHAR,
  SOURCE_BATCH_ID VARCHAR,
  PIPELINE_CREATED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
