-- Scaffold-only SILVER DDL for dataset: branch_location
-- TODO: replace placeholder columns with curated model design.
CREATE TABLE IF NOT EXISTS FRAUDLENS.SILVER.SILVER_BRANCH_LOCATION (
  PLACEHOLDER_RECORD_ID VARCHAR,
  SOURCE_BATCH_ID VARCHAR,
  PIPELINE_CREATED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
