-- Stage 3 (#41): Bronze core/fraud operations table foundation

-- dataset: party
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_PARTY (
  PARTY_ID VARCHAR,
  PARTY_TYPE VARCHAR,
  PARTY_STATUS VARCHAR,
  DOMICILE_COUNTRY_CODE VARCHAR,
  RISK_SEGMENT_CODE VARCHAR,
  CUSTOMER_SEGMENT_CODE VARCHAR,
  CUSTOMER_TYPE_CODE VARCHAR,
  INDUSTRY_SECTOR_CODE VARCHAR,
  RESIDENCY_REGION_ID VARCHAR,
  CUSTOMER_SINCE_AT TIMESTAMP_NTZ,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: party_org_assignment
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_PARTY_ORG_ASSIGNMENT (
  PARTY_ORG_ASSIGNMENT_ID VARCHAR,
  PARTY_ID VARCHAR,
  BUSINESS_UNIT_ID VARCHAR,
  ANALYST_TEAM_ID VARCHAR,
  BRANCH_ID VARCHAR,
  ASSIGNMENT_ROLE_CODE VARCHAR,
  EFFECTIVE_FROM_AT TIMESTAMP_NTZ,
  EFFECTIVE_TO_AT TIMESTAMP_NTZ,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: deposit_account
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_DEPOSIT_ACCOUNT (
  DEPOSIT_ACCOUNT_ID VARCHAR,
  ACCOUNT_STATUS VARCHAR,
  PRODUCT_TYPE_CODE VARCHAR,
  PRIMARY_PARTY_ID VARCHAR,
  ACCOUNT_CURRENCY_CODE VARCHAR,
  AVAILABLE_BALANCE_AMOUNT NUMBER(18,2),
  OPENED_AT TIMESTAMP_NTZ,
  OPENED_BRANCH_ID VARCHAR,
  SERVICING_BUSINESS_UNIT_ID VARCHAR,
  ACCOUNT_REGION_ID VARCHAR,
  CLOSED_AT TIMESTAMP_NTZ,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: payment_card
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_PAYMENT_CARD (
  CARD_ID VARCHAR,
  LINKED_ACCOUNT_ID VARCHAR,
  CARD_STATUS VARCHAR,
  CARD_NETWORK_CODE VARCHAR,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: device_profile
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_DEVICE_PROFILE (
  DEVICE_ID VARCHAR,
  DEVICE_STATUS VARCHAR,
  OPERATING_SYSTEM_CODE VARCHAR,
  DEVICE_RISK_BAND VARCHAR,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: channel_event
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_CHANNEL_EVENT (
  CHANNEL_EVENT_ID VARCHAR,
  CHANNEL_CODE VARCHAR,
  SESSION_ID VARCHAR,
  BRANCH_ID VARCHAR,
  EVENT_AT TIMESTAMP_NTZ,
  EVENT_COUNTRY_CODE VARCHAR,
  IP_COUNTRY_CODE VARCHAR,
  AUTHENTICATION_RESULT_CODE VARCHAR,
  SESSION_RISK_CODE VARCHAR,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: payment_instruction
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_PAYMENT_INSTRUCTION (
  PAYMENT_INSTRUCTION_ID VARCHAR,
  INSTRUCTION_STATUS VARCHAR,
  DEBTOR_ACCOUNT_ID VARCHAR,
  DEBTOR_PARTY_ID VARCHAR,
  CREDITOR_PARTY_ID VARCHAR,
  INSTRUCTED_AMOUNT NUMBER(18,2),
  INSTRUCTED_CURRENCY_CODE VARCHAR,
  PAYMENT_PURPOSE_CODE VARCHAR,
  CHANNEL_EVENT_ID VARCHAR,
  CARD_ID VARCHAR,
  DEVICE_ID VARCHAR,
  EVENT_AT TIMESTAMP_NTZ,
  PAYMENT_RAIL_CODE VARCHAR,
  IS_CROSS_BORDER BOOLEAN,
  MERCHANT_COUNTRY_CODE VARCHAR,
  COUNTERPARTY_BANK_COUNTRY_CODE VARCHAR,
  BOOKING_DATE DATE,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: payment_transaction
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_PAYMENT_TRANSACTION (
  PAYMENT_TRANSACTION_ID VARCHAR,
  PAYMENT_INSTRUCTION_ID VARCHAR,
  TRANSACTION_STATUS VARCHAR,
  BOOKING_AMOUNT NUMBER(18,2),
  TRANSACTION_CURRENCY_CODE VARCHAR,
  SETTLEMENT_AT TIMESTAMP_NTZ,
  MERCHANT_CATEGORY_CODE VARCHAR,
  REVERSAL_REASON_CODE VARCHAR,
  POSTED_DATE DATE,
  VALUE_DATE DATE,
  TRANSACTION_DIRECTION_CODE VARCHAR,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: risk_signal
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_RISK_SIGNAL (
  RISK_SIGNAL_ID VARCHAR,
  PAYMENT_INSTRUCTION_ID VARCHAR,
  SIGNAL_TYPE_CODE VARCHAR,
  SIGNAL_SCORE_AMOUNT NUMBER(18,2),
  RISK_LEVEL VARCHAR,
  EVENT_AT TIMESTAMP_NTZ,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: fraud_alert
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_FRAUD_ALERT (
  FRAUD_ALERT_ID VARCHAR,
  RISK_SIGNAL_ID VARCHAR,
  ALERT_STATUS VARCHAR,
  ALERT_SEVERITY VARCHAR,
  QUEUE_CODE VARCHAR,
  CREATED_AT TIMESTAMP_NTZ,
  ALERT_TYPE_CODE VARCHAR,
  ALERT_SOURCE_CODE VARCHAR,
  OWNING_BUSINESS_UNIT_ID VARCHAR,
  OWNING_ANALYST_TEAM_ID VARCHAR,
  SERVICE_LEVEL_DUE_AT TIMESTAMP_NTZ,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: fraud_case
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_FRAUD_CASE (
  FRAUD_CASE_ID VARCHAR,
  PRIMARY_ALERT_ID VARCHAR,
  CASE_STATUS VARCHAR,
  ASSIGNED_ANALYST_PARTY_ID VARCHAR,
  OPENED_AT TIMESTAMP_NTZ,
  CLOSED_AT TIMESTAMP_NTZ,
  CASE_TYPE_CODE VARCHAR,
  CASE_PRIORITY_CODE VARCHAR,
  OWNING_BUSINESS_UNIT_ID VARCHAR,
  OWNING_ANALYST_TEAM_ID VARCHAR,
  HANDLING_REGION_ID VARCHAR,
  ESCALATION_LEVEL_CODE VARCHAR,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: investigation_event
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_INVESTIGATION_EVENT (
  INVESTIGATION_EVENT_ID VARCHAR,
  FRAUD_CASE_ID VARCHAR,
  INVESTIGATION_EVENT_TYPE VARCHAR,
  ACTOR_PARTY_ID VARCHAR,
  EVENT_AT TIMESTAMP_NTZ,
  EVENT_RESULT_CODE VARCHAR,
  ELAPSED_MINUTES NUMBER(9,0),
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: decision_record
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_DECISION_RECORD (
  DECISION_ID VARCHAR,
  FRAUD_CASE_ID VARCHAR,
  DECISION_TYPE VARCHAR,
  DECISION_STATUS VARCHAR,
  DECISION_MAKER_PARTY_ID VARCHAR,
  DECIDED_AT TIMESTAMP_NTZ,
  DECISION_REASON_CODE VARCHAR,
  DECISION_CHANNEL_CODE VARCHAR,
  POLICY_NAME VARCHAR,
  RULE_SET_VERSION VARCHAR,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: case_disposition
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_CASE_DISPOSITION (
  DISPOSITION_ID VARCHAR,
  DECISION_ID VARCHAR,
  DISPOSITION_CODE VARCHAR,
  FINANCIAL_IMPACT_AMOUNT NUMBER(18,2),
  OUTCOME_AT TIMESTAMP_NTZ,
  LOSS_AMOUNT NUMBER(18,2),
  RECOVERED_AMOUNT NUMBER(18,2),
  WRITE_OFF_AMOUNT NUMBER(18,2),
  RECOVERY_STATUS_CODE VARCHAR,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
