-- Stage 3 (#41): Bronze dimension table foundation

-- dataset: reference_data_catalog
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_REFERENCE_DATA_CATALOG (
  CODE_SET_NAME VARCHAR,
  CODE_VALUE VARCHAR,
  CODE_DESCRIPTION VARCHAR,
  IS_ACTIVE BOOLEAN,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: calendar_day
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_CALENDAR_DAY (
  CALENDAR_DATE DATE,
  CALENDAR_YEAR NUMBER(9,0),
  CALENDAR_QUARTER NUMBER(9,0),
  CALENDAR_MONTH NUMBER(9,0),
  CALENDAR_MONTH_NAME VARCHAR,
  WEEK_OF_YEAR NUMBER(9,0),
  DAY_OF_WEEK NUMBER(9,0),
  DAY_NAME VARCHAR,
  IS_WEEKEND BOOLEAN,
  IS_MONTH_END BOOLEAN,
  IS_QUARTER_END BOOLEAN,
  IS_HOLIDAY BOOLEAN,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: region
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_REGION (
  REGION_ID VARCHAR,
  REGION_CODE VARCHAR,
  REGION_NAME VARCHAR,
  COUNTRY_GROUP_CODE VARCHAR,
  IS_ACTIVE BOOLEAN,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: branch_territory
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_BRANCH_TERRITORY (
  BRANCH_TERRITORY_ID VARCHAR,
  BRANCH_TERRITORY_CODE VARCHAR,
  BRANCH_TERRITORY_NAME VARCHAR,
  REGION_ID VARCHAR,
  IS_ACTIVE BOOLEAN,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: branch_location
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_BRANCH_LOCATION (
  BRANCH_ID VARCHAR,
  BRANCH_CODE VARCHAR,
  BRANCH_NAME VARCHAR,
  BRANCH_TERRITORY_ID VARCHAR,
  REGION_ID VARCHAR,
  COUNTRY_CODE VARCHAR,
  CITY_NAME VARCHAR,
  IS_ACTIVE BOOLEAN,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: business_unit
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_BUSINESS_UNIT (
  BUSINESS_UNIT_ID VARCHAR,
  BUSINESS_UNIT_CODE VARCHAR,
  BUSINESS_UNIT_NAME VARCHAR,
  BUSINESS_UNIT_TYPE VARCHAR,
  REGION_ID VARCHAR,
  IS_ACTIVE BOOLEAN,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- dataset: analyst_team
CREATE TABLE IF NOT EXISTS FRAUDLENS.BRONZE.BRONZE_ANALYST_TEAM (
  ANALYST_TEAM_ID VARCHAR,
  ANALYST_TEAM_CODE VARCHAR,
  ANALYST_TEAM_NAME VARCHAR,
  BUSINESS_UNIT_ID VARCHAR,
  REGION_ID VARCHAR,
  IS_ACTIVE BOOLEAN,
  INGESTION_BATCH_ID VARCHAR,
  SOURCE_FILE_NAME VARCHAR,
  INGESTED_AT_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
