-- Stage 4 (#42): standard CSV file format for FraudLens Bronze ingestion

CREATE FILE FORMAT IF NOT EXISTS FRAUDLENS.BRONZE.FF_BRONZE_CSV_V1
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', 'NULL', 'null')
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;
