-- Phase 3 Stage 2 (#40): role and privilege baseline
-- Run with a privileged admin role.

CREATE ROLE IF NOT EXISTS FRAUDLENS_ENGINEER_ROLE;

GRANT USAGE ON WAREHOUSE FRAUDLENS_WH_XS TO ROLE FRAUDLENS_ENGINEER_ROLE;
GRANT USAGE ON DATABASE FRAUDLENS TO ROLE FRAUDLENS_ENGINEER_ROLE;

GRANT USAGE ON SCHEMA FRAUDLENS.BRONZE TO ROLE FRAUDLENS_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA FRAUDLENS.SILVER TO ROLE FRAUDLENS_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA FRAUDLENS.GOLD TO ROLE FRAUDLENS_ENGINEER_ROLE;

GRANT CREATE TABLE ON SCHEMA FRAUDLENS.BRONZE TO ROLE FRAUDLENS_ENGINEER_ROLE;
GRANT CREATE TABLE ON SCHEMA FRAUDLENS.SILVER TO ROLE FRAUDLENS_ENGINEER_ROLE;
GRANT CREATE TABLE ON SCHEMA FRAUDLENS.GOLD TO ROLE FRAUDLENS_ENGINEER_ROLE;
